/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
const documents = {
  '\n      query Carts($filters: CartFiltersInput, $pagination: PaginationArg) {\n        carts(filters: $filters, pagination: $pagination) {\n          documentId\n          item {\n            id\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.CartsDocument,
  '\n      mutation CreateCart($data: CartInput!) {\n        createCart(data: $data) {\n          documentId\n          item {\n            productID\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          user {\n            username\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.CreateCartDocument,
  '\n      mutation UpdateCart($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n          item {\n            productID\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          user {\n            username\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.UpdateCartDocument,
  '\n      mutation DeleteCart($documentId: ID!) {\n        deleteCart(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeleteCartDocument,
  '\n      query Files($filters: FilesFiltersArgs) {\n        files(filters: $filters) {\n          documentId\n          name\n          alternativeText\n          caption\n          width\n          height\n          formats\n          hash\n          ext\n          mime\n          size\n          url\n          previewUrl\n          provider\n          provider_metadata\n        }\n      }\n    ':
    types.FilesDocument,
  '\n      mutation CreateOrder($data: OrderInput!) {\n        createOrder(data: $data) {\n          documentId\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.CreateOrderDocument,
  '\n      query Pages {\n        pages {\n          documentId\n          title\n          slug\n        }\n      }\n    ':
    types.PagesDocument,
  '\n      query GetPage($slug: String!) {\n        getPage(slug: $slug) {\n          documentId\n          title\n          slug\n          sections {\n            ... on ComponentSectionsWarehouseLocations {\n              id\n              heading\n              sub_heading\n              locations {\n                id\n                address\n                warehouse_time\n                office_time\n                google_maps_link\n                name\n              }\n            }\n            ... on ComponentSectionsContactUs {\n              id\n              heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsContactDetails {\n              id\n              left_heading\n              left_sub_heading\n              right_heading\n              right_sub_heading\n            }\n            ... on ComponentSectionsAbout {\n              id\n              heading\n              sub_heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsImageSlider {\n              id\n              animation_duration\n              display_button\n              slides {\n                id\n                title\n                description\n                link\n                image {\n                  name\n                  alternativeText\n                  url\n                }\n                type\n              }\n            }\n            ... on ComponentFormNewsletter {\n              id\n              heading\n              sub_heading\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n              sub_text\n              button_title\n              image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentFormInquiry {\n              id\n              heading\n              button_title\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n            }\n            ... on Error {\n              code\n              message\n            }\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.GetPageDocument,
  '\n      query Products(\n        $filters: ProductFiltersInput\n        $pagination: PaginationArg\n      ) {\n        products(filters: $filters, pagination: $pagination) {\n          documentId\n          name\n          description\n          category\n          vendor\n          model\n          odoo_product_id\n          product_brand_image {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.ProductsDocument,
  '\n      query Product($documentId: ID!) {\n        product(documentId: $documentId) {\n          documentId\n          name\n          description\n          category\n          vendor\n          model\n          odoo_product_id\n          product_brand_image {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.ProductDocument,
  '\n      mutation CreateProduct($data: ProductInput!) {\n        createProduct(data: $data) {\n          documentId\n          name\n          model\n          description\n          category\n          vendor\n          odoo_product_id\n          inventories {\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.CreateProductDocument,
  '\n      mutation CustomProductUpdate($documentId: ID!, $data: ProductInput!) {\n        customProductUpdate(documentId: $documentId, data: $data) {\n          documentId\n          name\n          model\n          description\n          category\n          vendor\n          odoo_product_id\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          specification {\n            id\n            key\n            value\n          }\n          files {\n            documentId\n            name\n            url\n            mime\n            ext\n          }\n          images {\n            documentId\n            name\n            url\n            mime\n            ext\n          }\n          key_features {\n            id\n            feature\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.CustomProductUpdateDocument,
  '\n      query User($filters: UserFiltersInput) {\n        user(filters: $filters) {\n          documentId\n          email\n          account_status\n          blocked\n          username\n          business_name\n          business_number\n          user_type\n          phone\n          role {\n            name\n          }\n          carts {\n            documentId\n            item {\n              productID\n              title\n              quantity\n              price\n              odoo_product_id\n              model\n              image\n            }\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            createdAt\n            updatedAt\n          }\n          account_detail {\n            phone\n            level\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            shipping_addresses {\n              documentId\n              phone\n              name {\n                first_name\n                middle_name\n                last_name\n              }\n              street1\n              street2\n              city\n              state\n              zip_code\n              country\n              isActive\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    ':
    types.UserDocument,
  '\n      query UsersPermissionsUsers {\n        usersPermissionsUsers {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          user_type\n          phone\n          addresses {\n            documentId\n            street1\n            street2\n            city\n            state\n            zip_code\n            country\n            isActive\n            phone\n            city\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n          }\n          role {\n            name\n          }\n        }\n      }\n    ':
    types.UsersPermissionsUsersDocument,
  '\n      query UsersPermissionsUser($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          role {\n            name\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            odoo_user_id\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    ':
    types.UsersPermissionsUserDocument,
  '\n      mutation Login($input: UsersPermissionsLoginInput!) {\n        login(input: $input) {\n          jwt\n          user {\n            id\n            email\n            confirmed\n            blocked\n            username\n          }\n        }\n      }\n    ':
    types.LoginDocument,
  '\n      mutation RegisterUser($data: RegisterUserInput!) {\n        registerUser(data: $data) {\n          documentId\n        }\n      }\n    ':
    types.RegisterUserDocument,
  '\n      mutation ApprovedUser($data: ApprovedUserInput!, $documentId: ID!) {\n        approvedUser(data: $data, documentId: $documentId) {\n          documentId\n          email\n        }\n      }\n    ':
    types.ApprovedUserDocument,
  '\n      mutation UpdateUser($documentId: ID!, $data: UsersPermissionsUserInput!) {\n        updateUser(documentId: $documentId, data: $data) {\n          account_status\n        }\n      }\n    ':
    types.UpdateUserDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Carts($filters: CartFiltersInput, $pagination: PaginationArg) {\n        carts(filters: $filters, pagination: $pagination) {\n          documentId\n          item {\n            id\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      query Carts($filters: CartFiltersInput, $pagination: PaginationArg) {\n        carts(filters: $filters, pagination: $pagination) {\n          documentId\n          item {\n            id\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateCart($data: CartInput!) {\n        createCart(data: $data) {\n          documentId\n          item {\n            productID\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          user {\n            username\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateCart($data: CartInput!) {\n        createCart(data: $data) {\n          documentId\n          item {\n            productID\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          user {\n            username\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateCart($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n          item {\n            productID\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          user {\n            username\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateCart($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n          item {\n            productID\n            title\n            quantity\n            price\n            odoo_product_id\n            model\n            image\n          }\n          user {\n            username\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation DeleteCart($documentId: ID!) {\n        deleteCart(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation DeleteCart($documentId: ID!) {\n        deleteCart(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Files($filters: FilesFiltersArgs) {\n        files(filters: $filters) {\n          documentId\n          name\n          alternativeText\n          caption\n          width\n          height\n          formats\n          hash\n          ext\n          mime\n          size\n          url\n          previewUrl\n          provider\n          provider_metadata\n        }\n      }\n    '
): (typeof documents)['\n      query Files($filters: FilesFiltersArgs) {\n        files(filters: $filters) {\n          documentId\n          name\n          alternativeText\n          caption\n          width\n          height\n          formats\n          hash\n          ext\n          mime\n          size\n          url\n          previewUrl\n          provider\n          provider_metadata\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateOrder($data: OrderInput!) {\n        createOrder(data: $data) {\n          documentId\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateOrder($data: OrderInput!) {\n        createOrder(data: $data) {\n          documentId\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Pages {\n        pages {\n          documentId\n          title\n          slug\n        }\n      }\n    '
): (typeof documents)['\n      query Pages {\n        pages {\n          documentId\n          title\n          slug\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query GetPage($slug: String!) {\n        getPage(slug: $slug) {\n          documentId\n          title\n          slug\n          sections {\n            ... on ComponentSectionsWarehouseLocations {\n              id\n              heading\n              sub_heading\n              locations {\n                id\n                address\n                warehouse_time\n                office_time\n                google_maps_link\n                name\n              }\n            }\n            ... on ComponentSectionsContactUs {\n              id\n              heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsContactDetails {\n              id\n              left_heading\n              left_sub_heading\n              right_heading\n              right_sub_heading\n            }\n            ... on ComponentSectionsAbout {\n              id\n              heading\n              sub_heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsImageSlider {\n              id\n              animation_duration\n              display_button\n              slides {\n                id\n                title\n                description\n                link\n                image {\n                  name\n                  alternativeText\n                  url\n                }\n                type\n              }\n            }\n            ... on ComponentFormNewsletter {\n              id\n              heading\n              sub_heading\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n              sub_text\n              button_title\n              image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentFormInquiry {\n              id\n              heading\n              button_title\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n            }\n            ... on Error {\n              code\n              message\n            }\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      query GetPage($slug: String!) {\n        getPage(slug: $slug) {\n          documentId\n          title\n          slug\n          sections {\n            ... on ComponentSectionsWarehouseLocations {\n              id\n              heading\n              sub_heading\n              locations {\n                id\n                address\n                warehouse_time\n                office_time\n                google_maps_link\n                name\n              }\n            }\n            ... on ComponentSectionsContactUs {\n              id\n              heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsContactDetails {\n              id\n              left_heading\n              left_sub_heading\n              right_heading\n              right_sub_heading\n            }\n            ... on ComponentSectionsAbout {\n              id\n              heading\n              sub_heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsImageSlider {\n              id\n              animation_duration\n              display_button\n              slides {\n                id\n                title\n                description\n                link\n                image {\n                  name\n                  alternativeText\n                  url\n                }\n                type\n              }\n            }\n            ... on ComponentFormNewsletter {\n              id\n              heading\n              sub_heading\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n              sub_text\n              button_title\n              image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentFormInquiry {\n              id\n              heading\n              button_title\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n            }\n            ... on Error {\n              code\n              message\n            }\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Products(\n        $filters: ProductFiltersInput\n        $pagination: PaginationArg\n      ) {\n        products(filters: $filters, pagination: $pagination) {\n          documentId\n          name\n          description\n          category\n          vendor\n          model\n          odoo_product_id\n          product_brand_image {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      query Products(\n        $filters: ProductFiltersInput\n        $pagination: PaginationArg\n      ) {\n        products(filters: $filters, pagination: $pagination) {\n          documentId\n          name\n          description\n          category\n          vendor\n          model\n          odoo_product_id\n          product_brand_image {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Product($documentId: ID!) {\n        product(documentId: $documentId) {\n          documentId\n          name\n          description\n          category\n          vendor\n          model\n          odoo_product_id\n          product_brand_image {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      query Product($documentId: ID!) {\n        product(documentId: $documentId) {\n          documentId\n          name\n          description\n          category\n          vendor\n          model\n          odoo_product_id\n          product_brand_image {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateProduct($data: ProductInput!) {\n        createProduct(data: $data) {\n          documentId\n          name\n          model\n          description\n          category\n          vendor\n          odoo_product_id\n          inventories {\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateProduct($data: ProductInput!) {\n        createProduct(data: $data) {\n          documentId\n          name\n          model\n          description\n          category\n          vendor\n          odoo_product_id\n          inventories {\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specification {\n            id\n            key\n            value\n          }\n          key_features {\n            id\n            feature\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CustomProductUpdate($documentId: ID!, $data: ProductInput!) {\n        customProductUpdate(documentId: $documentId, data: $data) {\n          documentId\n          name\n          model\n          description\n          category\n          vendor\n          odoo_product_id\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          specification {\n            id\n            key\n            value\n          }\n          files {\n            documentId\n            name\n            url\n            mime\n            ext\n          }\n          images {\n            documentId\n            name\n            url\n            mime\n            ext\n          }\n          key_features {\n            id\n            feature\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CustomProductUpdate($documentId: ID!, $data: ProductInput!) {\n        customProductUpdate(documentId: $documentId, data: $data) {\n          documentId\n          name\n          model\n          description\n          category\n          vendor\n          odoo_product_id\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          specification {\n            id\n            key\n            value\n          }\n          files {\n            documentId\n            name\n            url\n            mime\n            ext\n          }\n          images {\n            documentId\n            name\n            url\n            mime\n            ext\n          }\n          key_features {\n            id\n            feature\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query User($filters: UserFiltersInput) {\n        user(filters: $filters) {\n          documentId\n          email\n          account_status\n          blocked\n          username\n          business_name\n          business_number\n          user_type\n          phone\n          role {\n            name\n          }\n          carts {\n            documentId\n            item {\n              productID\n              title\n              quantity\n              price\n              odoo_product_id\n              model\n              image\n            }\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            createdAt\n            updatedAt\n          }\n          account_detail {\n            phone\n            level\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            shipping_addresses {\n              documentId\n              phone\n              name {\n                first_name\n                middle_name\n                last_name\n              }\n              street1\n              street2\n              city\n              state\n              zip_code\n              country\n              isActive\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query User($filters: UserFiltersInput) {\n        user(filters: $filters) {\n          documentId\n          email\n          account_status\n          blocked\n          username\n          business_name\n          business_number\n          user_type\n          phone\n          role {\n            name\n          }\n          carts {\n            documentId\n            item {\n              productID\n              title\n              quantity\n              price\n              odoo_product_id\n              model\n              image\n            }\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            createdAt\n            updatedAt\n          }\n          account_detail {\n            phone\n            level\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            shipping_addresses {\n              documentId\n              phone\n              name {\n                first_name\n                middle_name\n                last_name\n              }\n              street1\n              street2\n              city\n              state\n              zip_code\n              country\n              isActive\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query UsersPermissionsUsers {\n        usersPermissionsUsers {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          user_type\n          phone\n          addresses {\n            documentId\n            street1\n            street2\n            city\n            state\n            zip_code\n            country\n            isActive\n            phone\n            city\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n          }\n          role {\n            name\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query UsersPermissionsUsers {\n        usersPermissionsUsers {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          user_type\n          phone\n          addresses {\n            documentId\n            street1\n            street2\n            city\n            state\n            zip_code\n            country\n            isActive\n            phone\n            city\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n          }\n          role {\n            name\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query UsersPermissionsUser($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          role {\n            name\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            odoo_user_id\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query UsersPermissionsUser($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          role {\n            name\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            odoo_user_id\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation Login($input: UsersPermissionsLoginInput!) {\n        login(input: $input) {\n          jwt\n          user {\n            id\n            email\n            confirmed\n            blocked\n            username\n          }\n        }\n      }\n    '
): (typeof documents)['\n      mutation Login($input: UsersPermissionsLoginInput!) {\n        login(input: $input) {\n          jwt\n          user {\n            id\n            email\n            confirmed\n            blocked\n            username\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation RegisterUser($data: RegisterUserInput!) {\n        registerUser(data: $data) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation RegisterUser($data: RegisterUserInput!) {\n        registerUser(data: $data) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation ApprovedUser($data: ApprovedUserInput!, $documentId: ID!) {\n        approvedUser(data: $data, documentId: $documentId) {\n          documentId\n          email\n        }\n      }\n    '
): (typeof documents)['\n      mutation ApprovedUser($data: ApprovedUserInput!, $documentId: ID!) {\n        approvedUser(data: $data, documentId: $documentId) {\n          documentId\n          email\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateUser($documentId: ID!, $data: UsersPermissionsUserInput!) {\n        updateUser(documentId: $documentId, data: $data) {\n          account_status\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateUser($documentId: ID!, $data: UsersPermissionsUserInput!) {\n        updateUser(documentId: $documentId, data: $data) {\n          account_status\n        }\n      }\n    '];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
