/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
const documents = {
  '\n      query Address($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          addresses {\n            city\n            country\n            documentId\n            isActive\n            mobile\n            odoo_address_id\n            phone\n            createdAt\n            state\n            street1\n            street2\n            title\n            zip_code\n          }\n        }\n      }\n    ':
    types.AddressDocument,
  '\n      mutation CreateAddress($data: AddressInput!) {\n        createAddress(data: $data) {\n          documentId\n        }\n      }\n    ':
    types.CreateAddressDocument,
  '\n      mutation DeleteAddress($documentId: ID!) {\n        deleteAddress(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeleteAddressDocument,
  '\n      mutation UpdateAddress($data: AddressInput!, $documentId: ID!) {\n        updateAddress(data: $data, documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.UpdateAddressDocument,
  '\n      mutation UpdateAddressIsActive($documentId: ID!, $data: AddressInput!) {\n        updateAddress(documentId: $documentId, data: $data) {\n          documentId\n        }\n      }\n    ':
    types.UpdateAddressIsActiveDocument,
  '\n      #graphql\n      query Carts($filters: CartFiltersInput, $pagination: PaginationArg) {\n        carts(filters: $filters, pagination: $pagination) {\n          documentId\n          product {\n            documentId\n            name\n            model\n            odoo_product_id\n            price_lists {\n              price\n              min_quantity\n              max_quantity\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.CartsDocument,
  '\n      query GetCheckoutUserData($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          carts {\n            documentId\n            quantity\n            product {\n              documentId\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n              }\n              shipping {\n                height\n                length\n                weight\n                width\n              }\n            }\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            title\n            odoo_address_id\n            mobile\n            createdAt\n            updatedAt\n          }\n          creditCards {\n            brand\n            documentId\n            expMonth\n            expYear\n            isDefault\n            last4Char\n            publishedAt\n            stripePaymentMethodID\n          }\n        }\n      }\n    ':
    types.GetCheckoutUserDataDocument,
  '\n      #graphql\n      mutation CreateCart($data: CartInput!) {\n        createCart(data: $data) {\n          documentId\n          product {\n            documentId\n            odoo_product_id\n            name\n            model\n            price_lists {\n              price\n              sale_price\n              min_quantity\n              max_quantity\n              user_level\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }  \n      }\n    ':
    types.CreateCartDocument,
  '\n      #graphql\n      mutation UpdateCart($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n          product {\n            documentId\n            name\n            model\n            odoo_product_id\n            price_lists {\n              price\n              sale_price\n              min_quantity\n              max_quantity\n              user_level\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.UpdateCartDocument,
  '\n      #graphql\n      mutation DeleteCart($documentId: ID!) {\n        deleteCart(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeleteCartDocument,
  '\n      #graphql\n      mutation UpdateQuantity($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n        }\n      }\n    ':
    types.UpdateQuantityDocument,
  '\n      query Collections($filters: CollectionFiltersInput) {\n        collections(filters: $filters) {\n          documentId\n          title\n          handle\n          sortOrder\n          productCount\n          image {\n            name\n            alternativeText\n            url\n          }\n        }\n      }\n    ':
    types.CollectionsDocument,
  '\n      query CollectionsWithProducts(\n        $collectionsFilters: CollectionFiltersInput, \n        $productsFilters: ProductFiltersInput, \n        $productsPagination: PaginationArg\n      ) {\n        collections(filters: $collectionsFilters) {\n          documentId\n          handle\n          sortOrder\n          productCount\n          image {\n            name\n            alternativeText\n            url\n          }\n          productFilters {\n            id\n            title\n            handle\n          }\n          products(\n            filters: $productsFilters,\n            pagination: $productsPagination,\n          ) {\n            documentId\n              name\n              description\n              vendor\n              product_type\n              model\n              odoo_product_id\n              categories {\n                title\n                slug\n                image {\n                  documentId\n                  name\n                  alternativeText\n                  width\n                  height\n                  mime\n                  url\n                }\n              }\n              brand {\n                documentId\n                name\n                url\n                image {\n                  documentId\n                  name\n                  alternativeText\n                  width\n                  height\n                  mime\n                  url\n                }\n              }\n              price_lists {\n                documentId\n                price\n                sale_price\n                min_quantity\n                max_quantity\n                user_level\n              }\n              files {\n                documentId\n                name\n                alternativeText\n                width\n                height\n                mime\n                url\n              }\n              images {\n                documentId\n                name\n                alternativeText\n                width\n                height\n                mime\n                url\n              }\n              specifications {\n                documentId\n                key\n                value\n              }\n              key_features {\n                documentId\n                feature\n              }\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n                createdAt\n                updatedAt\n                publishedAt\n              }\n              createdAt\n              updatedAt\n              publishedAt\n            }\n          }\n        }\n    ':
    types.CollectionsWithProductsDocument,
  '\n      mutation CreateCreditCard($data: CreditCardInput!) {\n        createCreditCard(data: $data) {\n          documentId\n        }\n      }\n    ':
    types.CreateCreditCardDocument,
  '\n      mutation UpdateCreditCard($data: CreditCardInput!, $documentId: ID!) {\n        updateCreditCard(data: $data, documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.UpdateCreditCardDocument,
  '\n      mutation DeleteCreditCard($documentId: ID!) {\n        deleteCreditCard(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeleteCreditCardDocument,
  '\n      query Files($filters: FilesFiltersArgs) {\n        files(filters: $filters) {\n          documentId\n          name\n          alternativeText\n          caption\n          width\n          height\n          formats\n          hash\n          ext\n          mime\n          size\n          url\n          previewUrl\n          provider\n          provider_metadata\n        }\n      }\n    ':
    types.FilesDocument,
  '\n      query Orders($filters: OrderFiltersInput) {\n        orders(filters: $filters) {\n          documentId\n          orderNumber\n          user {\n            documentId\n            business_name\n          }\n          total {\n            amount\n            currency\n          }\n          paymentStatus\n          fulfillmentStatus\n\n          paymentMethod\n          shippingType\n          deliveryStatus\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.OrdersDocument,
  '\n      mutation CreateOrder($data: OrderInput!) {\n        createOrder(data: $data) {\n          documentId\n        }\n      }\n    ':
    types.CreateOrderDocument,
  '\n      query Pages {\n        pages {\n          documentId\n          title\n          slug\n        }\n      }\n    ':
    types.PagesDocument,
  '\n      query GetPage($slug: String!) {\n        getPage(slug: $slug) {\n          documentId\n          title\n          slug\n          sections {\n            ... on ComponentSectionsWarehouseLocations {\n              id\n              heading\n              sub_heading\n              locations {\n                id\n                address\n                warehouse_time\n                office_time\n                google_maps_link\n                name\n              }\n            }\n            ... on ComponentSectionsContactUs {\n              id\n              heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsContactDetails {\n              id\n              left_heading\n              left_sub_heading\n              right_heading\n              right_sub_heading\n            }\n            ... on ComponentSectionsAbout {\n              id\n              heading\n              sub_heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsImageSlider {\n              id\n              animation_duration\n              display_button\n              slides {\n                id\n                title\n                description\n                link\n                image {\n                  name\n                  alternativeText\n                  url\n                }\n                type\n              }\n            }\n            ... on ComponentFormNewsletter {\n              id\n              heading\n              sub_heading\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n              sub_text\n              button_title\n              image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentFormInquiry {\n              id\n              heading\n              button_title\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n            }\n            ... on Error {\n              code\n              message\n            }\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.GetPageDocument,
  '\n      query Products(\n        $filters: ProductFiltersInput\n        $pagination: PaginationArg\n      ) {\n        products(filters: $filters, pagination: $pagination) {\n          documentId\n          name\n          description\n          product_type\n          vendor\n          model\n          odoo_product_id\n          categories {\n            title\n            slug\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          brand {\n            documentId\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          shipping {\n            height\n            width\n            length\n            weight\n          }\n          createdAt\n          updatedAt\n          releasedAt\n        }\n      }\n    ':
    types.ProductsDocument,
  '\n      query Product($documentId: ID!) {\n        product(documentId: $documentId) {\n          documentId\n          name\n          description\n          vendor\n          product_type\n          model\n          odoo_product_id\n          categories {\n            title\n            slug\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          brand {\n            documentId\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          shipping {\n            height\n            width\n            length\n            weight\n          }\n          createdAt\n          updatedAt\n          releasedAt\n        }\n      }\n    ':
    types.ProductDocument,
  '\n      query Brands($filters: BrandFiltersInput) {\n        brands(filters: $filters) {\n          documentId\n          name\n          url\n          image {\n            name\n            alternativeText\n            mime\n            url\n            width\n            height\n          }\n        }\n      }\n    ':
    types.BrandsDocument,
  '\n      query Categories {\n        categories {\n          documentId\n          title\n          slug\n          image {\n            name\n            alternativeText\n            mime\n            url\n            width\n            height\n          }\n        }\n      }\n    ':
    types.CategoriesDocument,
  '\n      query Specifications {\n        specifications {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.SpecificationsDocument,
  '\n      mutation CustomProductCreate($data: ProductInput!) {\n        customProductCreate(data: $data) {\n          documentId\n          name\n          model\n          description\n          vendor\n          odoo_product_id\n          brand {\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          shipping {\n            documentId\n            width\n            height\n            weight\n            length\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.CustomProductCreateDocument,
  '\n      mutation customProductUpdate($documentId: ID!, $data: ProductInput!) {\n        customProductUpdate(documentId: $documentId, data: $data) {\n          documentId\n          name\n          model\n          description\n          vendor\n          odoo_product_id\n          brand {\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          shipping {\n            documentId\n            width\n            height\n            weight\n            length\n          }\n          createdAt\n          updatedAt\n          releasedAt\n          # status\n          improvedBy {\n            email\n          }\n          madeBy {\n            email\n          }\n        }\n      }\n    ':
    types.CustomProductUpdateDocument,
  '\n      mutation CreatePrice($data: PriceInput!) {\n        createPrice(data: $data) {\n          documentId\n          sale_price\n          price\n          min_quantity\n          max_quantity\n          user_level\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.CreatePriceDocument,
  '\n      mutation UpdatePrice($documentId: ID!, $data: PriceInput!) {\n        updatePrice(documentId: $documentId, data: $data) {\n          documentId\n          sale_price\n          price\n          min_quantity\n          max_quantity\n          user_level\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.UpdatePriceDocument,
  '\n      mutation DeletePrice($documentId: ID!) {\n        deletePrice(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeletePriceDocument,
  '\n      mutation CreateInventory($data: InventoryInput!) {\n        createInventory(data: $data) {\n          documentId\n          name\n          location_code\n          quantity\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.CreateInventoryDocument,
  '\n      mutation UpdateInventory($documentId: ID!, $data: InventoryInput!) {\n        updateInventory(documentId: $documentId, data: $data) {\n          documentId\n          name\n          location_code\n          quantity\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.UpdateInventoryDocument,
  '\n      mutation DeleteInventory($documentId: ID!) {\n        deleteInventory(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeleteInventoryDocument,
  '\n      mutation CreateSpecification($data: SpecificationInput!) {\n        createSpecification(data: $data) {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.CreateSpecificationDocument,
  '\n      mutation UpdateSpecification(\n        $documentId: ID!\n        $data: SpecificationInput!\n      ) {\n        updateSpecification(documentId: $documentId, data: $data) {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.UpdateSpecificationDocument,
  '\n      mutation DeleteSpecification($documentId: ID!) {\n        deleteSpecification(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeleteSpecificationDocument,
  '\n      mutation CreateKeyFeature($data: KeyFeatureInput!) {\n        createKeyFeature(data: $data) {\n          documentId\n          feature\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.CreateKeyFeatureDocument,
  '\n      mutation UpdateKeyFeature($documentId: ID!, $data: KeyFeatureInput!) {\n        updateKeyFeature(documentId: $documentId, data: $data) {\n          documentId\n          feature\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    ':
    types.UpdateKeyFeatureDocument,
  '\n      mutation DeleteKeyFeature($documentId: ID!) {\n        deleteKeyFeature(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeleteKeyFeatureDocument,
  '\n      mutation CreateShipping($data: ShippingInput!) {\n        createShipping(data: $data) {\n          documentId\n          width\n          height\n          weight\n          length\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.CreateShippingDocument,
  '\n      mutation UpdateShipping($documentId: ID!, $data: ShippingInput!) {\n        updateShipping(documentId: $documentId, data: $data) {\n          documentId\n          width\n          height\n          weight\n          length\n          createdAt\n          updatedAt\n        }\n      }\n    ':
    types.UpdateShippingDocument,
  '\n      mutation DeleteShipping($documentId: ID!) {\n        deleteShipping(documentId: $documentId) {\n          documentId\n        }\n      }\n    ':
    types.DeleteShippingDocument,
  '\n      query UsersPermissionsUser($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          documentId\n          email\n          account_status\n          blocked\n          username\n          business_name\n          business_number\n          business_type\n          phone\n          role {\n            name\n          }\n          carts {\n            documentId\n            quantity\n            product {\n              documentId\n              name\n              model\n              odoo_product_id\n              price_lists {\n                price\n                sale_price\n                min_quantity\n                max_quantity\n                user_level\n              }\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n              }\n              shipping {\n                height\n                length\n                weight\n                width\n              }\n              images {\n                url\n                alternativeText\n                width\n                height\n              }\n            }\n            createdAt\n            updatedAt\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            createdAt\n            updatedAt\n          }\n          account_detail {\n            phone\n            level\n            odoo_user_id\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            shipping_addresses {\n              documentId\n              phone\n              street1\n              street2\n              city\n              state\n              zip_code\n              country\n              isActive\n              name {\n                first_name\n                middle_name\n                last_name\n              }\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    ':
    types.UsersPermissionsUserDocument,
  '\n      query UsersPermissionsUsers {\n        usersPermissionsUsers {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          business_type\n          phone\n          addresses {\n            documentId\n            street1\n            street2\n            city\n            state\n            zip_code\n            country\n            isActive\n            phone\n            city\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n          }\n          role {\n            name\n          }\n        }\n      }\n    ':
    types.UsersPermissionsUsersDocument,
  '\n      mutation Login($input: UsersPermissionsLoginInput!) {\n        login(input: $input) {\n          jwt\n          user {\n            documentId\n            email\n            confirmed\n            blocked\n            username\n          }\n        }\n      }\n    ':
    types.LoginDocument,
  '\n      mutation RegisterUser($data: RegisterUserInput!) {\n        registerUser(data: $data) {\n          documentId\n        }\n      }\n    ':
    types.RegisterUserDocument,
  '\n      mutation ApprovedUser($data: ApprovedUserInput!, $documentId: ID!) {\n        approvedUser(data: $data, documentId: $documentId) {\n          documentId\n          email\n        }\n      }\n    ':
    types.ApprovedUserDocument,
  '\n      mutation UpdateUser($documentId: ID!, $data: UsersPermissionsUserInput!) {\n        updateUser(documentId: $documentId, data: $data) {\n          account_status\n        }\n      }\n    ':
    types.UpdateUserDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Address($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          addresses {\n            city\n            country\n            documentId\n            isActive\n            mobile\n            odoo_address_id\n            phone\n            createdAt\n            state\n            street1\n            street2\n            title\n            zip_code\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query Address($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          addresses {\n            city\n            country\n            documentId\n            isActive\n            mobile\n            odoo_address_id\n            phone\n            createdAt\n            state\n            street1\n            street2\n            title\n            zip_code\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateAddress($data: AddressInput!) {\n        createAddress(data: $data) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateAddress($data: AddressInput!) {\n        createAddress(data: $data) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation DeleteAddress($documentId: ID!) {\n        deleteAddress(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation DeleteAddress($documentId: ID!) {\n        deleteAddress(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateAddress($data: AddressInput!, $documentId: ID!) {\n        updateAddress(data: $data, documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateAddress($data: AddressInput!, $documentId: ID!) {\n        updateAddress(data: $data, documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateAddressIsActive($documentId: ID!, $data: AddressInput!) {\n        updateAddress(documentId: $documentId, data: $data) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateAddressIsActive($documentId: ID!, $data: AddressInput!) {\n        updateAddress(documentId: $documentId, data: $data) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      #graphql\n      query Carts($filters: CartFiltersInput, $pagination: PaginationArg) {\n        carts(filters: $filters, pagination: $pagination) {\n          documentId\n          product {\n            documentId\n            name\n            model\n            odoo_product_id\n            price_lists {\n              price\n              min_quantity\n              max_quantity\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      #graphql\n      query Carts($filters: CartFiltersInput, $pagination: PaginationArg) {\n        carts(filters: $filters, pagination: $pagination) {\n          documentId\n          product {\n            documentId\n            name\n            model\n            odoo_product_id\n            price_lists {\n              price\n              min_quantity\n              max_quantity\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query GetCheckoutUserData($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          carts {\n            documentId\n            quantity\n            product {\n              documentId\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n              }\n              shipping {\n                height\n                length\n                weight\n                width\n              }\n            }\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            title\n            odoo_address_id\n            mobile\n            createdAt\n            updatedAt\n          }\n          creditCards {\n            brand\n            documentId\n            expMonth\n            expYear\n            isDefault\n            last4Char\n            publishedAt\n            stripePaymentMethodID\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query GetCheckoutUserData($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          carts {\n            documentId\n            quantity\n            product {\n              documentId\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n              }\n              shipping {\n                height\n                length\n                weight\n                width\n              }\n            }\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            title\n            odoo_address_id\n            mobile\n            createdAt\n            updatedAt\n          }\n          creditCards {\n            brand\n            documentId\n            expMonth\n            expYear\n            isDefault\n            last4Char\n            publishedAt\n            stripePaymentMethodID\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      #graphql\n      mutation CreateCart($data: CartInput!) {\n        createCart(data: $data) {\n          documentId\n          product {\n            documentId\n            odoo_product_id\n            name\n            model\n            price_lists {\n              price\n              sale_price\n              min_quantity\n              max_quantity\n              user_level\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }  \n      }\n    '
): (typeof documents)['\n      #graphql\n      mutation CreateCart($data: CartInput!) {\n        createCart(data: $data) {\n          documentId\n          product {\n            documentId\n            odoo_product_id\n            name\n            model\n            price_lists {\n              price\n              sale_price\n              min_quantity\n              max_quantity\n              user_level\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }  \n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      #graphql\n      mutation UpdateCart($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n          product {\n            documentId\n            name\n            model\n            odoo_product_id\n            price_lists {\n              price\n              sale_price\n              min_quantity\n              max_quantity\n              user_level\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      #graphql\n      mutation UpdateCart($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n          product {\n            documentId\n            name\n            model\n            odoo_product_id\n            price_lists {\n              price\n              sale_price\n              min_quantity\n              max_quantity\n              user_level\n            }\n            inventories {\n              documentId\n              name\n              location_code\n              quantity\n            }\n            images {\n              url\n              alternativeText\n              width\n              height\n            }\n          }\n          user {\n            documentId\n            username\n          }\n          quantity\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      #graphql\n      mutation DeleteCart($documentId: ID!) {\n        deleteCart(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      #graphql\n      mutation DeleteCart($documentId: ID!) {\n        deleteCart(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      #graphql\n      mutation UpdateQuantity($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      #graphql\n      mutation UpdateQuantity($documentId: ID!, $data: CartInput!) {\n        updateCart(documentId: $documentId, data: $data) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Collections($filters: CollectionFiltersInput) {\n        collections(filters: $filters) {\n          documentId\n          title\n          handle\n          sortOrder\n          productCount\n          image {\n            name\n            alternativeText\n            url\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query Collections($filters: CollectionFiltersInput) {\n        collections(filters: $filters) {\n          documentId\n          title\n          handle\n          sortOrder\n          productCount\n          image {\n            name\n            alternativeText\n            url\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query CollectionsWithProducts(\n        $collectionsFilters: CollectionFiltersInput, \n        $productsFilters: ProductFiltersInput, \n        $productsPagination: PaginationArg\n      ) {\n        collections(filters: $collectionsFilters) {\n          documentId\n          handle\n          sortOrder\n          productCount\n          image {\n            name\n            alternativeText\n            url\n          }\n          productFilters {\n            id\n            title\n            handle\n          }\n          products(\n            filters: $productsFilters,\n            pagination: $productsPagination,\n          ) {\n            documentId\n              name\n              description\n              vendor\n              product_type\n              model\n              odoo_product_id\n              categories {\n                title\n                slug\n                image {\n                  documentId\n                  name\n                  alternativeText\n                  width\n                  height\n                  mime\n                  url\n                }\n              }\n              brand {\n                documentId\n                name\n                url\n                image {\n                  documentId\n                  name\n                  alternativeText\n                  width\n                  height\n                  mime\n                  url\n                }\n              }\n              price_lists {\n                documentId\n                price\n                sale_price\n                min_quantity\n                max_quantity\n                user_level\n              }\n              files {\n                documentId\n                name\n                alternativeText\n                width\n                height\n                mime\n                url\n              }\n              images {\n                documentId\n                name\n                alternativeText\n                width\n                height\n                mime\n                url\n              }\n              specifications {\n                documentId\n                key\n                value\n              }\n              key_features {\n                documentId\n                feature\n              }\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n                createdAt\n                updatedAt\n                publishedAt\n              }\n              createdAt\n              updatedAt\n              publishedAt\n            }\n          }\n        }\n    '
): (typeof documents)['\n      query CollectionsWithProducts(\n        $collectionsFilters: CollectionFiltersInput, \n        $productsFilters: ProductFiltersInput, \n        $productsPagination: PaginationArg\n      ) {\n        collections(filters: $collectionsFilters) {\n          documentId\n          handle\n          sortOrder\n          productCount\n          image {\n            name\n            alternativeText\n            url\n          }\n          productFilters {\n            id\n            title\n            handle\n          }\n          products(\n            filters: $productsFilters,\n            pagination: $productsPagination,\n          ) {\n            documentId\n              name\n              description\n              vendor\n              product_type\n              model\n              odoo_product_id\n              categories {\n                title\n                slug\n                image {\n                  documentId\n                  name\n                  alternativeText\n                  width\n                  height\n                  mime\n                  url\n                }\n              }\n              brand {\n                documentId\n                name\n                url\n                image {\n                  documentId\n                  name\n                  alternativeText\n                  width\n                  height\n                  mime\n                  url\n                }\n              }\n              price_lists {\n                documentId\n                price\n                sale_price\n                min_quantity\n                max_quantity\n                user_level\n              }\n              files {\n                documentId\n                name\n                alternativeText\n                width\n                height\n                mime\n                url\n              }\n              images {\n                documentId\n                name\n                alternativeText\n                width\n                height\n                mime\n                url\n              }\n              specifications {\n                documentId\n                key\n                value\n              }\n              key_features {\n                documentId\n                feature\n              }\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n                createdAt\n                updatedAt\n                publishedAt\n              }\n              createdAt\n              updatedAt\n              publishedAt\n            }\n          }\n        }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateCreditCard($data: CreditCardInput!) {\n        createCreditCard(data: $data) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateCreditCard($data: CreditCardInput!) {\n        createCreditCard(data: $data) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateCreditCard($data: CreditCardInput!, $documentId: ID!) {\n        updateCreditCard(data: $data, documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateCreditCard($data: CreditCardInput!, $documentId: ID!) {\n        updateCreditCard(data: $data, documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation DeleteCreditCard($documentId: ID!) {\n        deleteCreditCard(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation DeleteCreditCard($documentId: ID!) {\n        deleteCreditCard(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Files($filters: FilesFiltersArgs) {\n        files(filters: $filters) {\n          documentId\n          name\n          alternativeText\n          caption\n          width\n          height\n          formats\n          hash\n          ext\n          mime\n          size\n          url\n          previewUrl\n          provider\n          provider_metadata\n        }\n      }\n    '
): (typeof documents)['\n      query Files($filters: FilesFiltersArgs) {\n        files(filters: $filters) {\n          documentId\n          name\n          alternativeText\n          caption\n          width\n          height\n          formats\n          hash\n          ext\n          mime\n          size\n          url\n          previewUrl\n          provider\n          provider_metadata\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Orders($filters: OrderFiltersInput) {\n        orders(filters: $filters) {\n          documentId\n          orderNumber\n          user {\n            documentId\n            business_name\n          }\n          total {\n            amount\n            currency\n          }\n          paymentStatus\n          fulfillmentStatus\n\n          paymentMethod\n          shippingType\n          deliveryStatus\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      query Orders($filters: OrderFiltersInput) {\n        orders(filters: $filters) {\n          documentId\n          orderNumber\n          user {\n            documentId\n            business_name\n          }\n          total {\n            amount\n            currency\n          }\n          paymentStatus\n          fulfillmentStatus\n\n          paymentMethod\n          shippingType\n          deliveryStatus\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateOrder($data: OrderInput!) {\n        createOrder(data: $data) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateOrder($data: OrderInput!) {\n        createOrder(data: $data) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Pages {\n        pages {\n          documentId\n          title\n          slug\n        }\n      }\n    '
): (typeof documents)['\n      query Pages {\n        pages {\n          documentId\n          title\n          slug\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query GetPage($slug: String!) {\n        getPage(slug: $slug) {\n          documentId\n          title\n          slug\n          sections {\n            ... on ComponentSectionsWarehouseLocations {\n              id\n              heading\n              sub_heading\n              locations {\n                id\n                address\n                warehouse_time\n                office_time\n                google_maps_link\n                name\n              }\n            }\n            ... on ComponentSectionsContactUs {\n              id\n              heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsContactDetails {\n              id\n              left_heading\n              left_sub_heading\n              right_heading\n              right_sub_heading\n            }\n            ... on ComponentSectionsAbout {\n              id\n              heading\n              sub_heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsImageSlider {\n              id\n              animation_duration\n              display_button\n              slides {\n                id\n                title\n                description\n                link\n                image {\n                  name\n                  alternativeText\n                  url\n                }\n                type\n              }\n            }\n            ... on ComponentFormNewsletter {\n              id\n              heading\n              sub_heading\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n              sub_text\n              button_title\n              image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentFormInquiry {\n              id\n              heading\n              button_title\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n            }\n            ... on Error {\n              code\n              message\n            }\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      query GetPage($slug: String!) {\n        getPage(slug: $slug) {\n          documentId\n          title\n          slug\n          sections {\n            ... on ComponentSectionsWarehouseLocations {\n              id\n              heading\n              sub_heading\n              locations {\n                id\n                address\n                warehouse_time\n                office_time\n                google_maps_link\n                name\n              }\n            }\n            ... on ComponentSectionsContactUs {\n              id\n              heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsContactDetails {\n              id\n              left_heading\n              left_sub_heading\n              right_heading\n              right_sub_heading\n            }\n            ... on ComponentSectionsAbout {\n              id\n              heading\n              sub_heading\n              description\n              button_title\n              background_image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentSectionsImageSlider {\n              id\n              animation_duration\n              display_button\n              slides {\n                id\n                title\n                description\n                link\n                image {\n                  name\n                  alternativeText\n                  url\n                }\n                type\n              }\n            }\n            ... on ComponentFormNewsletter {\n              id\n              heading\n              sub_heading\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n              sub_text\n              button_title\n              image {\n                name\n                alternativeText\n                url\n              }\n            }\n            ... on ComponentFormInquiry {\n              id\n              heading\n              button_title\n              inputs {\n                id\n                label\n                type\n                placeholder\n                required\n              }\n            }\n            ... on Error {\n              code\n              message\n            }\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Products(\n        $filters: ProductFiltersInput\n        $pagination: PaginationArg\n      ) {\n        products(filters: $filters, pagination: $pagination) {\n          documentId\n          name\n          description\n          product_type\n          vendor\n          model\n          odoo_product_id\n          categories {\n            title\n            slug\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          brand {\n            documentId\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          shipping {\n            height\n            width\n            length\n            weight\n          }\n          createdAt\n          updatedAt\n          releasedAt\n        }\n      }\n    '
): (typeof documents)['\n      query Products(\n        $filters: ProductFiltersInput\n        $pagination: PaginationArg\n      ) {\n        products(filters: $filters, pagination: $pagination) {\n          documentId\n          name\n          description\n          product_type\n          vendor\n          model\n          odoo_product_id\n          categories {\n            title\n            slug\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          brand {\n            documentId\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          shipping {\n            height\n            width\n            length\n            weight\n          }\n          createdAt\n          updatedAt\n          releasedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Product($documentId: ID!) {\n        product(documentId: $documentId) {\n          documentId\n          name\n          description\n          vendor\n          product_type\n          model\n          odoo_product_id\n          categories {\n            title\n            slug\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          brand {\n            documentId\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          shipping {\n            height\n            width\n            length\n            weight\n          }\n          createdAt\n          updatedAt\n          releasedAt\n        }\n      }\n    '
): (typeof documents)['\n      query Product($documentId: ID!) {\n        product(documentId: $documentId) {\n          documentId\n          name\n          description\n          vendor\n          product_type\n          model\n          odoo_product_id\n          categories {\n            title\n            slug\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          brand {\n            documentId\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          images {\n            documentId\n            name\n            alternativeText\n            width\n            height\n            mime\n            url\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          inventories {\n            documentId\n            name\n            location_code\n            quantity\n            createdAt\n            updatedAt\n            publishedAt\n          }\n          shipping {\n            height\n            width\n            length\n            weight\n          }\n          createdAt\n          updatedAt\n          releasedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Brands($filters: BrandFiltersInput) {\n        brands(filters: $filters) {\n          documentId\n          name\n          url\n          image {\n            name\n            alternativeText\n            mime\n            url\n            width\n            height\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query Brands($filters: BrandFiltersInput) {\n        brands(filters: $filters) {\n          documentId\n          name\n          url\n          image {\n            name\n            alternativeText\n            mime\n            url\n            width\n            height\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Categories {\n        categories {\n          documentId\n          title\n          slug\n          image {\n            name\n            alternativeText\n            mime\n            url\n            width\n            height\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query Categories {\n        categories {\n          documentId\n          title\n          slug\n          image {\n            name\n            alternativeText\n            mime\n            url\n            width\n            height\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query Specifications {\n        specifications {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      query Specifications {\n        specifications {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CustomProductCreate($data: ProductInput!) {\n        customProductCreate(data: $data) {\n          documentId\n          name\n          model\n          description\n          vendor\n          odoo_product_id\n          brand {\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          shipping {\n            documentId\n            width\n            height\n            weight\n            length\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CustomProductCreate($data: ProductInput!) {\n        customProductCreate(data: $data) {\n          documentId\n          name\n          model\n          description\n          vendor\n          odoo_product_id\n          brand {\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          shipping {\n            documentId\n            width\n            height\n            weight\n            length\n          }\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation customProductUpdate($documentId: ID!, $data: ProductInput!) {\n        customProductUpdate(documentId: $documentId, data: $data) {\n          documentId\n          name\n          model\n          description\n          vendor\n          odoo_product_id\n          brand {\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          shipping {\n            documentId\n            width\n            height\n            weight\n            length\n          }\n          createdAt\n          updatedAt\n          releasedAt\n          # status\n          improvedBy {\n            email\n          }\n          madeBy {\n            email\n          }\n        }\n      }\n    '
): (typeof documents)['\n      mutation customProductUpdate($documentId: ID!, $data: ProductInput!) {\n        customProductUpdate(documentId: $documentId, data: $data) {\n          documentId\n          name\n          model\n          description\n          vendor\n          odoo_product_id\n          brand {\n            name\n            url\n            image {\n              documentId\n              name\n              alternativeText\n              width\n              height\n              mime\n              url\n            }\n          }\n          inventories {\n            documentId\n            location_code\n            quantity\n          }\n          price_lists {\n            documentId\n            price\n            sale_price\n            min_quantity\n            max_quantity\n            user_level\n          }\n          files {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          images {\n            documentId\n            mime\n            name\n            url\n            alternativeText\n          }\n          specifications {\n            documentId\n            key\n            value\n          }\n          key_features {\n            documentId\n            feature\n          }\n          shipping {\n            documentId\n            width\n            height\n            weight\n            length\n          }\n          createdAt\n          updatedAt\n          releasedAt\n          # status\n          improvedBy {\n            email\n          }\n          madeBy {\n            email\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreatePrice($data: PriceInput!) {\n        createPrice(data: $data) {\n          documentId\n          sale_price\n          price\n          min_quantity\n          max_quantity\n          user_level\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreatePrice($data: PriceInput!) {\n        createPrice(data: $data) {\n          documentId\n          sale_price\n          price\n          min_quantity\n          max_quantity\n          user_level\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdatePrice($documentId: ID!, $data: PriceInput!) {\n        updatePrice(documentId: $documentId, data: $data) {\n          documentId\n          sale_price\n          price\n          min_quantity\n          max_quantity\n          user_level\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdatePrice($documentId: ID!, $data: PriceInput!) {\n        updatePrice(documentId: $documentId, data: $data) {\n          documentId\n          sale_price\n          price\n          min_quantity\n          max_quantity\n          user_level\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation DeletePrice($documentId: ID!) {\n        deletePrice(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation DeletePrice($documentId: ID!) {\n        deletePrice(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateInventory($data: InventoryInput!) {\n        createInventory(data: $data) {\n          documentId\n          name\n          location_code\n          quantity\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateInventory($data: InventoryInput!) {\n        createInventory(data: $data) {\n          documentId\n          name\n          location_code\n          quantity\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateInventory($documentId: ID!, $data: InventoryInput!) {\n        updateInventory(documentId: $documentId, data: $data) {\n          documentId\n          name\n          location_code\n          quantity\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateInventory($documentId: ID!, $data: InventoryInput!) {\n        updateInventory(documentId: $documentId, data: $data) {\n          documentId\n          name\n          location_code\n          quantity\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation DeleteInventory($documentId: ID!) {\n        deleteInventory(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation DeleteInventory($documentId: ID!) {\n        deleteInventory(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateSpecification($data: SpecificationInput!) {\n        createSpecification(data: $data) {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateSpecification($data: SpecificationInput!) {\n        createSpecification(data: $data) {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateSpecification(\n        $documentId: ID!\n        $data: SpecificationInput!\n      ) {\n        updateSpecification(documentId: $documentId, data: $data) {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateSpecification(\n        $documentId: ID!\n        $data: SpecificationInput!\n      ) {\n        updateSpecification(documentId: $documentId, data: $data) {\n          documentId\n          key\n          value\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation DeleteSpecification($documentId: ID!) {\n        deleteSpecification(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation DeleteSpecification($documentId: ID!) {\n        deleteSpecification(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateKeyFeature($data: KeyFeatureInput!) {\n        createKeyFeature(data: $data) {\n          documentId\n          feature\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateKeyFeature($data: KeyFeatureInput!) {\n        createKeyFeature(data: $data) {\n          documentId\n          feature\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateKeyFeature($documentId: ID!, $data: KeyFeatureInput!) {\n        updateKeyFeature(documentId: $documentId, data: $data) {\n          documentId\n          feature\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateKeyFeature($documentId: ID!, $data: KeyFeatureInput!) {\n        updateKeyFeature(documentId: $documentId, data: $data) {\n          documentId\n          feature\n          createdAt\n          updatedAt\n          publishedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation DeleteKeyFeature($documentId: ID!) {\n        deleteKeyFeature(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation DeleteKeyFeature($documentId: ID!) {\n        deleteKeyFeature(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation CreateShipping($data: ShippingInput!) {\n        createShipping(data: $data) {\n          documentId\n          width\n          height\n          weight\n          length\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation CreateShipping($data: ShippingInput!) {\n        createShipping(data: $data) {\n          documentId\n          width\n          height\n          weight\n          length\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateShipping($documentId: ID!, $data: ShippingInput!) {\n        updateShipping(documentId: $documentId, data: $data) {\n          documentId\n          width\n          height\n          weight\n          length\n          createdAt\n          updatedAt\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateShipping($documentId: ID!, $data: ShippingInput!) {\n        updateShipping(documentId: $documentId, data: $data) {\n          documentId\n          width\n          height\n          weight\n          length\n          createdAt\n          updatedAt\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation DeleteShipping($documentId: ID!) {\n        deleteShipping(documentId: $documentId) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation DeleteShipping($documentId: ID!) {\n        deleteShipping(documentId: $documentId) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query UsersPermissionsUser($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          documentId\n          email\n          account_status\n          blocked\n          username\n          business_name\n          business_number\n          business_type\n          phone\n          role {\n            name\n          }\n          carts {\n            documentId\n            quantity\n            product {\n              documentId\n              name\n              model\n              odoo_product_id\n              price_lists {\n                price\n                sale_price\n                min_quantity\n                max_quantity\n                user_level\n              }\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n              }\n              shipping {\n                height\n                length\n                weight\n                width\n              }\n              images {\n                url\n                alternativeText\n                width\n                height\n              }\n            }\n            createdAt\n            updatedAt\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            createdAt\n            updatedAt\n          }\n          account_detail {\n            phone\n            level\n            odoo_user_id\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            shipping_addresses {\n              documentId\n              phone\n              street1\n              street2\n              city\n              state\n              zip_code\n              country\n              isActive\n              name {\n                first_name\n                middle_name\n                last_name\n              }\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query UsersPermissionsUser($documentId: ID!) {\n        usersPermissionsUser(documentId: $documentId) {\n          documentId\n          email\n          account_status\n          blocked\n          username\n          business_name\n          business_number\n          business_type\n          phone\n          role {\n            name\n          }\n          carts {\n            documentId\n            quantity\n            product {\n              documentId\n              name\n              model\n              odoo_product_id\n              price_lists {\n                price\n                sale_price\n                min_quantity\n                max_quantity\n                user_level\n              }\n              inventories {\n                documentId\n                name\n                location_code\n                quantity\n              }\n              shipping {\n                height\n                length\n                weight\n                width\n              }\n              images {\n                url\n                alternativeText\n                width\n                height\n              }\n            }\n            createdAt\n            updatedAt\n          }\n          addresses {\n            documentId\n            street1\n            street2\n            state\n            city\n            zip_code\n            country\n            phone\n            isActive\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            createdAt\n            updatedAt\n          }\n          account_detail {\n            phone\n            level\n            odoo_user_id\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n            shipping_addresses {\n              documentId\n              phone\n              street1\n              street2\n              city\n              state\n              zip_code\n              country\n              isActive\n              name {\n                first_name\n                middle_name\n                last_name\n              }\n            }\n            warehouse_location {\n              title\n              address {\n                city\n                street\n                suburb\n                state_territory\n                postcode\n                country\n              }\n            }\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      query UsersPermissionsUsers {\n        usersPermissionsUsers {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          business_type\n          phone\n          addresses {\n            documentId\n            street1\n            street2\n            city\n            state\n            zip_code\n            country\n            isActive\n            phone\n            city\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n          }\n          role {\n            name\n          }\n        }\n      }\n    '
): (typeof documents)['\n      query UsersPermissionsUsers {\n        usersPermissionsUsers {\n          documentId\n          username\n          email\n          provider\n          blocked\n          account_status\n          business_name\n          business_number\n          business_type\n          phone\n          addresses {\n            documentId\n            street1\n            street2\n            city\n            state\n            zip_code\n            country\n            isActive\n            phone\n            city\n          }\n          account_detail {\n            documentId\n            level\n            phone\n            name {\n              first_name\n              middle_name\n              last_name\n            }\n          }\n          role {\n            name\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation Login($input: UsersPermissionsLoginInput!) {\n        login(input: $input) {\n          jwt\n          user {\n            documentId\n            email\n            confirmed\n            blocked\n            username\n          }\n        }\n      }\n    '
): (typeof documents)['\n      mutation Login($input: UsersPermissionsLoginInput!) {\n        login(input: $input) {\n          jwt\n          user {\n            documentId\n            email\n            confirmed\n            blocked\n            username\n          }\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation RegisterUser($data: RegisterUserInput!) {\n        registerUser(data: $data) {\n          documentId\n        }\n      }\n    '
): (typeof documents)['\n      mutation RegisterUser($data: RegisterUserInput!) {\n        registerUser(data: $data) {\n          documentId\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation ApprovedUser($data: ApprovedUserInput!, $documentId: ID!) {\n        approvedUser(data: $data, documentId: $documentId) {\n          documentId\n          email\n        }\n      }\n    '
): (typeof documents)['\n      mutation ApprovedUser($data: ApprovedUserInput!, $documentId: ID!) {\n        approvedUser(data: $data, documentId: $documentId) {\n          documentId\n          email\n        }\n      }\n    '];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n      mutation UpdateUser($documentId: ID!, $data: UsersPermissionsUserInput!) {\n        updateUser(documentId: $documentId, data: $data) {\n          account_status\n        }\n      }\n    '
): (typeof documents)['\n      mutation UpdateUser($documentId: ID!, $data: UsersPermissionsUserInput!) {\n        updateUser(documentId: $documentId, data: $data) {\n          account_status\n        }\n      }\n    '];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
