export enum USER_TYPE {
  INSTALLER = 'INSTALLER',
  RETAILER = 'RETAILER',
}

export enum USER_LEVEL {
  SMALL = 'SMALL',
  'MID-SIZED' = 'MID-SIZED',
  VIP = 'VIP',
}

export enum USER_STATUS {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
}
